- name: Print debug infomation eg1
  hosts: ceph2-node1
  remote_user: root
#  gather_facts: F
  vars:
     user: jingyong
  tasks:
      - name: Command run line
        shell: date
        register: result
      - name: Show debug info
        debug: var=result verbosity=0
