# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export GOPATH=/root/go_repo/

source /etc/git-completion.bash


#export http_proxy=http://10.168.89.1:7777
#export https_proxy=http://10.168.89.1:7777
