---
- name: install Vundle for vim 
  hosts: coder
  tasks:
    - file:
        state: directory
        path: "~/.vim/{{ item}}"
      with_items:
        - bundle
        - plugin

    - unarchive:
        src: taglist_46.zip
        dest: ~/.vim/

    - git: 
        repos: https://github.com/gmarik/Vundle.vim.git 
        dest: ~/.vim/bundle/Vundle.vim

    - command: cat vimrc.Vundle vimrc > ~/.vimrc 

    


