set fileencoding=utf-8
"set paste

set t_Co=256

filetype on

"语法高亮度显示 
syntax on 
"syntax enable 
""colorscheme slate
"
"""自动缩进 
set autoindent

"智能缩进 
""set smartindent
"
"""第一行设置tab键为4个空格，第二行设置当行之间交错时使用4个空格(方便写Python代码) 
set tabstop=4
set expandtab
set softtabstop=4
set shiftwidth=4

"匹配括号 
set showmatch

"TagList
"set Tlist_Auto_Open=1    "在启动 vim 后，自动打开 taglist 窗口。
"set Tlist_File_Fold_Auto_Close=1    "taglist 只显示当前文件
"tag，其它文件的tag折叠。 
""set Tlist_Use_Horiz_Window=1    "设置taglist窗口横向显示。

